version: '3.5'
volumes:
  postgres:

services:
  app:
    container_name: inconvenio-webshop-cart-service
    image: bigsmilez/inconvenio-webshop:cart-service
    command: java -jar target/cart-microservice-0.0.1-SNAPSHOT.jar
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    expose:
      - "5672"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: /postgres
    volumes:
      - postgres:/postgres
    restart: unless-stopped